name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,  macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Echo proxy
        run: |
          echo "android_home:$ANDROID_HOME"
          $ANDROID_HOME/

      - name: Upload
        shell: bash
        continue-on-error: true
        run: |
            ${ANDROID_HOME}/tools/bin/sdkmanager  --list>sdk_list.txt
            #######################################################################################################
            ######################################## upload files #################################################
            #######################################################################################################
            file_name=sdk_list.txt
            wget  https://github.com/hhhaiai/uploadGithub/releases/download/v1.1/uploadGithubService-1.1-jar-with-dependencies.jar
            dat=$(date "+%H%M%S")
            tpn=${{ github.repository }}
            pn=`echo $tpn | cut -d \/ -f 2`
            us=${{github.repository_owner}}
            echo "project name: $pn"
            today=$(date "+%Y%m%d")
            upload_file_name="ci/$today/$pn/${dat}-${file_name}"
            #upload_file_name="ci/${dat}-$pn-${file_name}"
            chmod -R 777 *
            echo "=================文件查看===================="
            ls
            echo "==dat== $dat"
            echo "==dat== $upload_file_name"
            # https://docs.github.com/cn/actions/learn-github-actions/contexts#github-context
            echo "===========================">>${file_name}
            echo "Project: ${{ github.repository }}">>${file_name}
            echo "Job: ${{ github.job }}">>${file_name}
            echo "Build commit sha: ${{ github.sha }}">>${file_name}
            echo "job.container.id: ${{ job.container.id }}">>${file_name}
            echo "job.container.network: ${{ job.container.network }}">>${file_name}
            java -jar uploadGithubService-1.1-jar-with-dependencies.jar  -owner hhhaiai -repo Git_result -target-dir-full-name  $upload_file_name -native-file ${file_name}  -token ${{ secrets.GTOKEN }} -commit-messge  "GitHubAction: Build commit ${{ github.sha }}. Project: ${{ github.repository }} Job ${{ github.job }}, created by ${{ github.workflow }} " -commit-auther "UploadGithubService" -commit-email "actions@github.com"
